version: 2

builds:
  - main: ./cmd/how
    binary: how
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

brews:
  - repository:
      owner: swibrow
      name: homebrew-tap
    homepage: https://github.com/swibrow/how
    description: "Smart terminal cheatsheet — ask a question, get a command"
    license: "MIT"
    install: |
      bin.install "how"
    test: |
      system "#{bin}/how", "--help"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
